### ISSUE TITLE
Question of Dataset Preprocessing

### ISSUE THREAD

**Issue by L-xia-C** [marukosan93/RS-rPPG#1]
Thank you for open-sourcing the code, but I still have some questions regarding the data preprocessing part.

Dataset1: ├── Sample1
├──├── mstmap.npy (contains [63,T,3] multi-scale spatial-temporal maps calculated from videos)
├──├── tmap.npy (contains [63,T,3] traditional augmentation calculated from the mstmaps by using create_tmaps_VIPL.sh)
├──├── bvp.npy (array with ground truth bvp signal [T])

In the above description, does T represent the total number of frames in the video, or is it the "T = 576 (19.2s at 30fps)" mentioned in the experimental section of the paper? If it's the latter, how is this 19.2 seconds selected from the video?

**Comment by marukosan93** [comment]
Hi, thanks for the questions and for your interest in our method. Good catch, for the data description T corresponds to the full length of the video, but for the method we use 576 frame long non-overlapping segments, I'll change the description to avoid confusion with the paper. You can check the code in "utils_sunet_folds_skin.py" under the function "window_dirs". Basically in that function we calculate the starting point of each non-overlaping segment and then pass it to the dataloader to select that exact segment from the whole video. E.g. for a video long 731 frames, only 1 segment from 0:576 is selected, for a video long 1200 frames two segments from 0:576 and 576:2*576 are selected.

**Comment by L-xia-C** [comment]
Thank you for your prompt and clear response.
