### ISSUE TITLE
Regarding the issue of positive and negative sample generation

### ISSUE THREAD

**Issue by L-xia-C** [marukosan93/RS-rPPG#3]
In the description of section III.B of the paper, the Anchor comes from MSTmap, while Positives P and Negatives N both come from Tmap.
![image](https://github.com/user-attachments/assets/1d501ec9-0e59-4147-b86e-08072c27fc57)
However, the train_rsrppg.py code doesn't seem to match the description, and I'm not sure if it's a misunderstanding on my part.
![image](https://github.com/user-attachments/assets/fff3e689-47a8-4f22-a47a-67d71164f659)

**Comment by marukosan93** [comment]
Hi, good catch, the code was slightly outdated, you should use output2 I updated the github. However, that's just a convention, in practice there is no real difference as after some gradient updates the anchor and positive get much closer in feature space, therefore produce similar outputs.

**Comment by L-xia-C** [comment]
I understand, thank you for the answer.
